### ISSUE TITLE
Click the login button but nothing happened

### ISSUE THREAD

**Issue by ewamtw** [ebenbruyns/junkstore#10]
I installed Beta 0.5 from Decky Store and installed the dependencies.

But when click the login button, nothing happened.

**Comment by ewamtw** [comment]
After deleted all junk-store folders in desktop mode, it can be login now.
But still shows no any game list of Epic.

**Comment by ebenbruyns** [comment]
This is an issue I need to fix, you can re-init the plugin from the about menu somewhere (sorry I'm traveling at the moment so I have limited access to things), once it's re-initialised it will build the database of games that it pulls from.

I will fix this asap.

**Comment by ewamtw** [comment]
It works! Thanks!

**Comment by ebenbruyns** [comment]
Glad to hear that. Have fun. More tweaks to come when I return home from my travels.

Jan 6, 2024 8:30:55 AM ewamtw ***@***.***>:

**Comment by ewamtw** [comment]
Have a nice trip and happy new year.
