### ISSUE TITLE
The application witch was not found

### ISSUE THREAD

**Issue by Isaacj6666** [ebenbruyns/junkstore#11]
got problem on install depedencies
![PXL_20240106_081224485](https://github.com/ebenbruyns/junkstore/assets/51056331/9115b0b0-906e-4b88-bdfa-e24c1731a9c6)

**Comment by Isaacj6666** [comment]
Had try below and reinstall plug in, but still not the same error:
After deleted all junk-store folders in desktop mode, it can be login now.

**Comment by ebenbruyns** [comment]
ugh, ok that's a flatpak dependency, maybe they've deleted it from the repo. I'll get a new flatpak out once I'm back home

**Comment by ebenbruyns** [comment]
Are you still getting this error? I'm just getting back into development on this plugin now. Have you got other flatpaks installed?

**Comment by ebenbruyns** [comment]
There's a new update coming that should hopefully resolve this issue

**Comment by Isaacj6666** [comment]
> There's a new update coming that should hopefully resolve this issue

Thanks for update. But the error still the same.
May I know any setting need run before this application?

**Comment by ebenbruyns** [comment]
any chance you can pop into the discord server?

**Comment by ebenbruyns** [comment]
I think if you run the install deps, go into desktop mode open the discover store, settings and enable the user repo it might work after that. I thought we had nailed this issue but clearly not yet.

**Comment by Isaacj6666** [comment]
> I think if you run the install deps, go into desktop mode open the discover store, settings and enable the user repo it might work after that. I thought we had nailed this issue but clearly not yet.

Just try update junkstore, it can installed  Dependencies correctly, and can login Epic account.

**Comment by ebenbruyns** [comment]
So you're all good now?

**Comment by Isaacj6666** [comment]
> So you're all good now?

Yes, log in, brow store and download game had no lroblem.
