### ISSUE TITLE
Login button does not redirect to the Epic Games Login shortcut

### ISSUE THREAD

**Issue by deekodes** [ebenbruyns/junkstore#15]
Also related to the huge error showing up when pressing "Login" on bazzite as mentioned in Discord.

**Comment by ebenbruyns** [comment]
We probably don't need steam_env anymore I used that to get GUI apps to work correctly without going through the rungame api, but that ultimately lead to too many problems. It may be useful in desktop mode though...

If that solves the problem we can run with it until more show up, we possibly could just now run it in game mode for now as well...

**Comment by deekodes** [comment]
I opened a PR with the fix, this should help with compatibility for now while steam envs are still being exported by the script
