### ISSUE TITLE
Games running only with "Run exe in game folder" or by removing launch arguments

### ISSUE THREAD

**Issue by Sarlic91** [ebenbruyns/junkstore#24]
**Describe the bug**
Games I installed won´t launch or get registred correctly.
All 3 of them won´t launch over Steam or normally over the Plugin. However, if I launch them over the Plugin with "Run exe in game folder" it starts without issues. Also if I remove the launch Options in Steam and let it launch the .exe directly it works. 

**To Reproduce**
I installed several games (Halcyon 6, Guacamelee 2, Hobs). All 3 of them downloaded and installed fast. Guacamelee 2 was added to the Steam Library twice. After reinstalling it was not added to Steam at all, after reinstalling a third time it appears to be installed correctly. Halcyon 6 is installed, but showed in my Steam Library as "2809912358" and the steam configuration page was empty. After a few minutes that changed and it was installed correctly. Hobs was installed correctly. 

**Expected behavior**
Games launching without manually removing the Epic Games Launch Arguments, maybe an option to set "Run exe in game folder" as Go-To option for a game

**Handheld device (please complete the following information):**
SteamDeck, newest stable release

**Additional context**
Found your app on reddit yesterday, Werewolf_Capable. Hope this can contribute something :)

**Comment by Sarlic91** [comment]
It was 0.8.4
I updated and will try another one

**Comment by Sarlic91** [comment]
Hob wont start, even with "Run exe", I will try to redownload Guacamelee 2

**Comment by ebenbruyns** [comment]
Ah good point, I should have said try reset launch options, there was a bug where launch options was set incorrectly - naturally those will survive through upgrades. The reset launch optons is kinda the magic make it work button, but be careful with it right now, saves are at risk if you abuse it.

**Comment by Sarlic91** [comment]
Found that one, good to know, thanks, but starting out i dont have any save to worry about 😁
Hob still wont start, tho I´m not sure it has to do with the plugin. The launcher (Run exe) just crashes me right back, same with just pressing "Play". If I Launch Hob.exe it says "Assertion Failed! Program (path to Hob.exe) File..\..\OgreMain\src\OgreRenderQueue.cpp Line: 115 Expression "pGroup && pTech" Press OK to exit the program, or Cancel to start the Wine debugger"

**Comment by ebenbruyns** [comment]
have you tried the latest proton GE.

That looks like its outside of my control. While Junk-Store might appear to be magic, it's sadly still limited to the same laws governing all Linux gaming

**Comment by Sarlic91** [comment]
Yeah, I tried some protons, I really don´t think thats the launcher 😁 Thank you, i will try some more stuff!

**Comment by ebenbruyns** [comment]
Can we close this issue then?

**Comment by Sarlic91** [comment]
Yes, thank you, I´ll open a new one if I need to

**Comment by ebenbruyns** [comment]
awesome, thank you for reporting this, I now have something else for the troubleshooting page on the wiki to add.
