### ISSUE TITLE
Unable to login, I keep getting an error "Unable to login, please call support"

### ISSUE THREAD

**Issue by superawdi** [ebenbruyns/junkstore#26]
No matter of method either by mail or steam account or gmail.

**Comment by skewby99** [comment]
Hey please have a look at the Wiki > Troubleshooting: 

[Unable to login](https://github.com/ebenbruyns/junkstore/wiki/Troubleshooting#when-i-try-to-login-it-says-unable-to-complete-login-what-do-i-do)

If you are still having issues after trying that, please jump in Discord and we can troubleshoot it further.
