### ISSUE TITLE
CAPTCHA Verify button is outside of mouse area

### ISSUE THREAD

**Issue by angelofrancisco** [ebenbruyns/junkstore#32]
**Describe the bug**
When trying to log in to Epic Game Store, I am asked to click on some images for CAPTCHA verification. However, the Verify button is below the allowed mouse  area for the Epic Games Login that is launched by Junk Store

**To Reproduce**
1. Fresh install of Junk Store
2. Click on Games in Junk Store
3. Click Login 
4. Epic Game Login launches
5. Input email address
6. Click Continue
7. CAPTCHA appears
8. Click on images required by CAPTCHA
9. Unable to click on Verify

**Expected behavior**
I expect the mouse to be able to move within the entire UI displayed so I can click on Verify when prompted

**Screenshots**

![image](https://github.com/ebenbruyns/junkstore/assets/1863548/a919862a-1b46-4dcb-a031-ac5f62d2c82e)
This is as far down I can move my cursor, which doesn't allow me to click on the Verify button. Tapping on the touch screen also does not work and only simulates a click in this region as well

**Handheld device (please complete the following information):**
 - Device: Steam Deck
 - OS: SteamOS 
 - Version 3.5.19

**Additional context**

**Comment by ebenbruyns** [comment]
Could you install dependencies again and tell me if this is still the case with the patched legendary flatpak?

Strictly this is not a junk-store issue but a legendary issue, but will keep this open for now
