### ISSUE TITLE
Red Dead Redemption 2 from EGS  Error 134

### ISSUE THREAD

**Issue by ZongerX** [ebenbruyns/junkstore#40]
Red Dead Redemption 2 from EGS cant run and show Rockstar Launcher error 134 after install

**To Reproduce**
1. Install game from EGS trough Junk-Store
2. Wait to install all Rockstar soft
3. Login into account
4. Close launcher after install
5. Launch RDR2
6. Take error 134

**Expected behavior**
Start game after initialize launcher

**Screenshots**

**Desktop (please complete the following information):**
 - OS: SteamOS Holo 
 - Version 3.5.19

**Handheld device (please complete the following information):**
 - Device: Steam Deck OLED
 - OS: SteamOS
 - Version 3.5.19

**Additional context**
I think Rockstar Launcher need to launch service with game to initialize run in offline mode, but RDR2 start solo and we see that problem. Some things happen in Heroic Launcher and i found some fix to this problem (not solve for me)

Need to create fix.bat with this parametrs:
>start /B "null" "C:\Program Files\Rockstar Games\Launcher\LauncherPatcher.exe"
>ping -n 20 localhost > nul
>./PlayRDR2.exe %*

It's mean game play with runned Rockstar Launcher, can u add this fix for play by default in GTAV and RDR2?

**Comment by ebenbruyns** [comment]
This is not a junk-store issue but a proton issue. You could try our discord server to see if anybody has found a work around.
