### ISSUE TITLE
Can no longer access any game in library

### ISSUE THREAD

**Issue by DrLegitamate** [ebenbruyns/junkstore#41]
**Describe the bug**
After installing junk store via the decky plugin store and installing dependencies. I am no longer able to access any game via game mode on steam deck. I am given this error:

Something went wrong while displaying this content. Refresh

Error Reference: Shared SteamUI_8869911_a2b046b6a9c9173e

Cannot read properties of undefined (reading 'InnerContainer')

**To Reproduce**
1. Go to decky plugin store
2. Click on install junk store
3. Install dependencies
4. Click any game in your library

**Expected behavior**
Be able to access and play games

**Handheld device (please complete the following information):**
 - Device: Steam Deck
 - OS: SteamOS
 - Version 3.5.19

**Additional context**
I have uninstalled junk store as well as tried different channels on steamos however my library is completely unusable

**Comment by ebenbruyns** [comment]
This sounds quite serious. Can you reboot your deck, do not open decky at all and do things work at this point?

If they do, try to open any other plugin in decky, does that work?

If all of the above work, open Junk-store, does the error occur now?

I'm just trying to assess on which layer this error is ocuring, usually this means that it's something wrong with decky loader, ie steam updated something that broke it, or the version of decky loader you are using is not compatible with Junk-Store. 

Valve recently released a version of Steam that caused chaos for the decky team, the symptoms are similar.

**Comment by DrLegitamate** [comment]
It seems that for a brief moment before the decky plugin loads and begins displaying notifications I am able to click on a game and open it however leaving the game and clicking on it again post decky plugin loading displays the same error

**Comment by ebenbruyns** [comment]
Is this in the plugin or in steam? Sorry, I'm being a bit pedantic, but I'm trying to get as many specifics as I can for this one.

**Comment by DrLegitamate** [comment]
No not a problem.

This is after restarting. The last played games load. I clicked the very latest one. It opened with the normal game viewer. While I had it open I got notifications from decky such as normal autoflatpak notifications. Once I closed the game view screen and was on the home menu, I clicked the very same game but was met with the error.

**Comment by DrLegitamate** [comment]
I was initially on stable when I installed junk store. I switched to pre release to see if that fixed the problem afterwards. No change either way

**Comment by ebenbruyns** [comment]
ok so if you uninstall Junk-Store (don't worry it won't touch your games etc), and try it again does it still happen?

I'm not 100% convinced it's Junk-Store related, but we have to make sure.

**Comment by ebenbruyns** [comment]
What other plugins do you have installed. I'm wondering if there's interplay maybe.

**Comment by DrLegitamate** [comment]
I have currently got junk store uninstalled. But the problem 100% started after it was installed. I had made no other changes nor updates to the steam deck. (I have since applied changes and updates though to attempt to fix the problem)

**Comment by DrLegitamate** [comment]
Plugins installed:

ProtonDB Badges
HLTB for deck
Steamback
Storage cleaner
Steam grid dB
Audio loader
Game theme music
Wine cellar
Controller tools
Is there any deal for deck
KDE connect
Music control

**Comment by ebenbruyns** [comment]
If Junk-Store is not installed, then it's impossible for my code to cause this, unless it's not properly uninstalled (This could be a decky issue).

This is going to be a pain to track down, but what you should do is uninstall decky and all plugins, then test that steam works. We have to track down what is responsible for this and what interplay is causing this.

Then install decky and make sure it all works with no plugins installed. If this is all clear install Junk-Store. If the issue occurs at this point it's 100% Junk-store and it will be related to the decky and or steam version (so I'll need those version numbers to figure out what's wrong).

If it works how ever, then you need to install the plugins 1 by 1 until you find the culprit, and naturally tell me which one it is so I can determine if it's something I can fix or something the other dev needs to fix.

I totally appreciate that this is a pain in the back side, but this is such a major issue that it requires a bit of effort and I really appreciate you doing this.

**Comment by ebenbruyns** [comment]
My gut instinct is telling me that it might be "Is there any deal for deck", but I have no evidence to support this other than an inkling.

**Comment by DrLegitamate** [comment]
I'll be going through all those steps now however just to keep you updated. I've just uninstalled decky loader and it's now working

**Comment by ebenbruyns** [comment]
Just a note, once you start installing plugins use the deck for a bit before you move onto the next one. My wife just suggested that there might be something that's laying in waiting for the ambush. I think I'll just listen to her on this one ;)

**Comment by DrLegitamate** [comment]
It seems that "Game theme music" was the culprit. Very odd as that has been installed for well over a year with no problem nor a recent update.

**Comment by ebenbruyns** [comment]
Yeah I suspect that decky was updated underneath it and it's not compatible with the version you're running. If you are happy that this issue is resolved from Junk-Store's perspective, you can close this issue.

Glad we got to the bottom of this one!

**Comment by ebenbruyns** [comment]
You're welcome, you had me worried for a second, but all good.
