### ISSUE TITLE
Website metadata is not configured

### ISSUE THREAD

**Issue by e-minguez** [ebenbruyns/junkstore#42]
**Describe the bug**
Sharing the website link via Telegram/WhatsApp/etc. shows a wrong site description 

**To Reproduce**
1. Go to 'junkstore.xyz'
2. Share it
3. See error

**Expected behavior**
Website metadata is showing a proper description 

**Screenshots**
![Screenshot_20240510-070504.png](https://github.com/ebenbruyns/junkstore/assets/346758/e72b6613-02ee-4035-8b35-2773f90f1b52)

**Desktop (please complete the following information):**
Not relevant 

**Handheld device (please complete the following information**

Not relevant 

**Additional context**
IIRC this is the site metadata being used when generating the previews.

**Comment by ebenbruyns** [comment]
ah thanks, the website is still very much a work in progress.

**Comment by mrsjunkrunner** [comment]
New website is now live and slick as ever.
