### ISSUE TITLE
Games Not Showing

### ISSUE THREAD

**Issue by dracinn** [ebenbruyns/junkstore#43]
I've logged in and my Epic Games library does not show, just a logout button.

**Comment by mrsjunkrunner** [comment]
yes this is a known issue that's been discussed in discord and reddit. there are two ways to fix it:  you can re-install v1.0 or you can install v1.1 from the Decky Testing Store.

let us know how you get on and if this solves your issue.

**Comment by dracinn** [comment]
Going to testing branch and updating fixed it thanks.
