### ISSUE TITLE
Store Launcher

### ISSUE THREAD

**Issue by dracinn** [ebenbruyns/junkstore#44]
I'd like if after clicking on the Steam button and selecting Store you have the option of Steam,Epic, or any future added marketplace.

**Comment by ebenbruyns** [comment]
I'm not likely to implement this, this alters the Steam UI significantly and is likely to break with steam updates. As a compromise, try version 1.1, enable developer mode in the about menu and then in the developer section enable the double stick option. Once enabled when you push down on both sticks you will get into junk-store.
