### ISSUE TITLE
Legendary dependency install fails

### ISSUE THREAD

**Issue by MattyXarope** [ebenbruyns/junkstore#5]
As of now, the dependency install for legendary fails as it requires org.gnome.Platform/x86_64/45 to work.

To remedy this, the user must install via command line:

`sudo flatpak install flathub org.gnome.Platform/x86_64/45`

**Comment by ebenbruyns** [comment]
I've pushed a change to install this first, I'm don't know if this will work on the steam deck, I don't have a deck with me at the moment. I'll be back with my deck in the next couple of days. If you could give it a whirl that would be good.

**Comment by ebenbruyns** [comment]
It's been a long time since this was reported, and it seems to be good now
