### ISSUE TITLE
Howto: reinstall Proton Easy Anti Cheat

### ISSUE THREAD

**Issue by bagage** [ebenbruyns/junkstore#52]
**Describe the bug**
I'd like to reinstall Proton Easy Anti Cheat to see if it could solve the issue I have (`Easy Anti cheat not initiated error in Fall guys)`. But the button is greyed out in `Dependencies` menu and even remove dependencies/reinstall them does not ungrey it.

**To Reproduce**
1. Go to Dependencies
2. Buttons `Install Proton EAC` and `Install Proton BattlEye Runtime` are greyed out and you can't interact with it

**Expected behavior**
We should be able to uninstall/reinstall anticheats

**Handheld device (please complete the following information):**
 - Device: Steam Deck
 - OS: SteamOS
 - Version 3.15.19

**Comment by mrsjunkrunner** [comment]
please read the wiki here you have missed a step: [Fall Guys help](https://wiki.junkstore.xyz/wiki/Help:Epic_Games/Working/Fall_Guys#If_you_already_have_Fall_Guys_installed%3A)
