### ISSUE TITLE
Error with Epic login

### ISSUE THREAD

**Issue by mbaran5** [ebenbruyns/junkstore#53]
**Describe the bug**
After logging into Epic, am given the error 

**ERROR**

ActionSet: EpicGamesLoginActions
ActionName: GetContent
Message: Error parsing json result Expecting value: line 2 column 1 (char 1)

**To Reproduce**
Install plugin (either 1.1 or 1.1.1 testing)
Log in to Epic (I removed special characters from my password based on other open issue)
Receive error

**Expected behavior**
No error should be shown. 

**Handheld device (please complete the following information):**
 - Device: Steam Deck
 - OS: SteamOS
 - Version 3.6.8

**Comment by mrsjunkrunner** [comment]
duplicate with issue #48

**Comment by mbaran5** [comment]
> duplicate with issue #48

This isn’t a dup. I can log in and see my games. I can install new games. Everything works. 

I just get the error every single time I get to the games view. 

Can you please re open this?

**Comment by mbaran5** [comment]
Additionally, this user on Discord is having the same issue https://discord.com/channels/1169048999618170880/1256586053834244178

**Comment by ebenbruyns** [comment]
Can you submit the logs produced after this error occurs?

**Comment by mbaran5** [comment]
Resolved with 1.1.2.
