### ISSUE TITLE
"Set game executable" does not work

### ISSUE THREAD

**Issue by krillme** [ebenbruyns/junkstore#54]
**Describe the bug**
After downloading Transistor from the Epic Games Store, it won't launch from the non-steam shortcut on Steam Deck unless you go into its entry in Junk Store, click "run exe in game folder" and select "Transistor.exe". If you click "set game executable" instead, the game will still not launch from the non-steam shortcut.

**To Reproduce**
1. Install Transistor from the Epic Games Store
2. Open the game through the non-steam shortcut. It will fail to launch 
3. Go to Transistor's entry in Junk Store and click the settings option
4. Click "run exe in game folder", then "Transistor.exe". The game will successfully launch
5. Return to Transistor's entry in Junk Store and click the settings option
6. Click "run exe in game folder", then "set game executable" when "Transistor.exe" is highlighted
7. Open the game through the non-steam shortcut. It will still fail to launch

**Expected behavior**
After clicking "set game executable" in Junk Store, the non-steam shortcut should successfully launch the game.

**Handheld device (please complete the following information):**
 - Device: Steam Deck OLED
 - OS: SteamOS
 - Version: 3.6.6

**Additional context**
It's possible this is caused by the game having an x86 and an x64 executable in the game folder.

**Comment by ebenbruyns** [comment]
There's quite a bit going on in that code. Does the Transitor.exe file accept the epic authentication arguments? At the moment there's no mechanism for disabling these. There's still quite a bit of design work that I need to do before I can implement a proper solution for this that will apply to all future store fronts.

**Comment by krillme** [comment]
How do I go about checking if the .exe accepts the epic authentication arguments? Are those not applied when you launch a game from the .exe instead of the non-steam shortcut?

**Comment by ebenbruyns** [comment]
If you launch it from the junk-store screen (assuming you didn't mess with the launch options or did a reset launch options) it will apply the epic args.

If you run it from the sliders menu it will run it without it.

The steam shortcut will run with the same settings that gets applied from the junk-store play button.

**Comment by ebenbruyns** [comment]
I have discovered a bug in this and I'm in the process of fixing it.

**Comment by krillme** [comment]
I apologize for not getting back to you on this, unfortunately my Steam Deck was out of commission. Good to hear that you found the problem, wish I could have been more helpful.

**Comment by mrsjunkrunner** [comment]
This has now been fixed with v1.1.8 which is now in the testing store.

Let us know if you have any further issues.
