### ISSUE TITLE
Please use the Epic Launcher to start the game. Connection to the Internet is required

### ISSUE THREAD

**Issue by ARRed98** [ebenbruyns/junkstore#57]
**Describe the bug**
I tried to install a game from epic with this plugin but when i launch the game i get this error. No way to go past it 

**To Reproduce**
Launch the game
The error appears
Press OK and the game closes
**Handheld device (please complete the following information):**
 - Device: Steam Deck
 - OS: SteamOS
 - Latest 3.6.8

**Comment by mrsjunkrunner** [comment]
Things to try:
- Make sure you are in online mode when launching the game.
- Open it first in desktop mode (some games require that for the first launch)
- If you are using v1.1.1 install the update for v1.1.2 (in stable store today)

**Comment by ARRed98** [comment]
The game is maneater. I already have the latest version of the plugin and even un desktop mode i get the same error

**Comment by mrsjunkrunner** [comment]
i just downloaded it and it launched straight away without issue. i'm using ProtonGE 9-7

how are you launching it?
which version of Proton are you using?
you could try the following and see which one works:
- reset launch options
- repair and update game

try one at a time and test by trying to launch the game.

**Comment by ARRed98** [comment]
Tried proton ge 9.9, 9.8 proton experimental and 9.0. I tried to launch it from the steam library, on the plugin page and on the desktop. It always gives me the same error

**Comment by mrsjunkrunner** [comment]
> Tried proton ge 9.9, 9.8 proton experimental and 9.0. 
Have you tried ProtonGE 9-7?

Did you try any of the other potential fixes from my previous comment?
- reset launch options
- repair and update game

try one at a time and test by trying to launch the game.

**Comment by ARRed98** [comment]
I tried with ge 9.7 it didn't work
i tried to reset the launch options didn't work
i tried to repair and update and didn't work either. 

Can some other plugins installed from decky impact junkstore?

**Comment by mrsjunkrunner** [comment]
> I tried with ge 9.7 it didn't work i tried to reset the launch options didn't work i tried to repair and update and didn't work either.
> 
> Can some other plugins installed from decky impact junkstore?

maybe...what plugins have you got installed?

**Comment by ARRed98** [comment]
CSS loader
Junk-store
ProtonDB Badges
SteamGridDB
Wine Cellar
EmuDecky

**Comment by mrsjunkrunner** [comment]
check you aren't in offline mode.
are you still logged into Epic?

sorry for the simple checks but this has happened before...

**Comment by mrsjunkrunner** [comment]
> CSS loader Junk-store ProtonDB Badges SteamGridDB Wine Cellar EmuDecky

none of those jump out as being an issue...

**Comment by ARRed98** [comment]
I tried to verify the game and i got an error
app/com.github.derrod.legandary?x86_64/master not installed

**Comment by ARRed98** [comment]
> check you aren't in offline mode. are you still logged into Epic?
> 
> sorry for the simple checks but this has happened before...

no problem i'll check

**Comment by mrsjunkrunner** [comment]
> I tried to verify the game and i got an error app/com.github.derrod.legandary?x86_64/master not installed

have you installed dependencies from the about menu?

**Comment by ARRed98** [comment]
Well reinstalling the plugin did the job. The game is launching. Still got some error while installing dependencies though... If i ever have a problem i'll come back with the logs. Thanks for the help and sorry for the time wasted

**Comment by mrsjunkrunner** [comment]
ok cool. curious about the error you're getting though, but good that it is working for you.

in future jump in our [discord server](https://discord.com/servers/junk-store-1169048999618170880) for support as github is for issues related to development not games or tech support.

we also like to track tech support issues there for others users to see and refer to if they have the same/similar problem.
