### ISSUE TITLE
Command produced no output: /bin/flatpak run com.github.derrod.legendary status --json

### ISSUE THREAD

**Issue by Jekotia** [ebenbruyns/junkstore#59]
**Describe the bug**
When attempting to install or launch a game, nothing happens for a few seconds and then an overlay with an error appears.

```
ActionSet:
ActionName:
Message: Command produced no output: /bin/flatpak run com.github.derrod.legendary status --json
```

Note that Junk store worked during initial setup and I was able to play Maneater. Since closing the game, however, I have not been able to install or launch anything.

**To Reproduce**
1. Attempt to launch or install a game

**Handheld device (please complete the following information):**
 - Device: Steam Deck
 - OS: SteamOS
 - SteamOS version 3.5.19, Decky version 2.12.3, Junk-Store Version 1.1.2, 

**Additional context**
I have restarted my device multiple times, as well as reinstalled Junk-Store. Neither has resulted in any changes in behaviour.

**Comment by ebenbruyns** [comment]
what's the ouput of
```bash
/bin/flatpak run com.github.derrod.legendary status --json
```

I have had a case where a user needed to log out manually using
```
/bin/flatpak run com.github.derrod.legendary auth --delete
```

which got them going again. I'm just wondering if there's an edge case I'm missing around login's expiring or something.  It's been pretty solid for most users, but this has got me wondering now.

**Comment by ebenbruyns** [comment]
Oh, I didn't read properly, your decky version is likely an issue here too. I'm not sure what version of Steam you're on but the latest steam update requires decky 3 (which is in the preview channel)

**Comment by Jekotia** [comment]
Just updated Decky to 3.0.0-pre5 on the pre-release channel, and it seems to have resolved the issue. Thank you! I didn't realise that Decky compatibility was like this, usually I catch this kind of thing myself :x
