### ISSUE TITLE
Epic install creates two Steam entries

### ISSUE THREAD

**Issue by MattyXarope** [ebenbruyns/junkstore#6]
When installing a game from Lengendary (Epic), two Steam shortcuts are made with identical information (in this case for the game Prey):

- Target:"Binaries/Danielle/x64-Epic/Release/Prey.exe"
- Start In:/home/deck/Games/PREY/Binaries/Danielle/x64-Epic/Release
- Launch Options:$(/home/deck/homebrew/plugins/Junk-Store/scripts/get-epic-args.sh 52d88e9a6df248da913c8e99f1e4c526)

![287921813-c8577427-a722-4f64-a95c-b766427138ff](https://github.com/ebenbruyns/junkstore/assets/30245871/3134159b-a6a8-41ae-a2d3-bf5085ee7bc2)

This seem erroneous. It should only produce one shortcut.

**Comment by ebenbruyns** [comment]
did you by chance navigate away while installing? There's a known limitation where I cannot easily catch if it's already installing and you start a second install.

I still need to come up with a good solution for this that will work for everyting.

**Comment by MattyXarope** [comment]
> did you by chance navigate away while installing? 

No, the screen was left on and I did not navigate away.

**Comment by ebenbruyns** [comment]
Closing this for now, it appears to be resolved, will reopen if it shows up again
