### ISSUE TITLE
Epic Login Button doesn't work - Multiple .sh files created

### ISSUE THREAD

**Issue by mrsjunkrunner** [ebenbruyns/junkstore#60]
**Describe the bug**
Trying to login via Epic and pushing the button does nothing. Has been found by multiple users that multiple .sh files get created.

**To Reproduce**
1. Install JS
2. Click on Login button in Epic tab

**Expected behavior**
Pushing login button in Epic tab will take me to login screen and allow me to enter login details.

**Update:** Please update to Junk-Store **v1.1.3** to fix this issue.

**Comment by VeMeth** [comment]
Is there a fix for this? Having exactly this problem.

**Comment by mrsjunkrunner** [comment]
> Is there a fix for this? Having exactly this problem.

Yes, sorry forgot to come back and add that to this once we found the issue and made a fix. 

You need to update Junk-Store to v1.1.3 in Decky Testing.

**Comment by mrsjunkrunner** [comment]
Fix has now been merged to main Decky store.

**Comment by VeMeth** [comment]
Thank you works perfectly now. So cool you were able to solve this so fast. Huge props!
