### ISSUE TITLE
Steamdeck: Retain Media Assets After Update

### ISSUE THREAD

**Issue by devertonh** [ebenbruyns/junkstore#64]
Upon updating a game within Junkstore (EPIC) the media assets (hero, horizontal grid, vertical grid, logo, and icon) are all reverted to the default that EPIC always uses. Every time the game is updated, the assets revert to what EPIC/Junkstore had them as default. 

I'd like to retain the existing media assets while still updating all other files. Maybe provide an opt in so it isn't the default for all uers. 

Some alternatives I've considered are redownloading all the assets but it usually takes a while and finding the same media assets is pretty painful. 

Game: Genshin Impact 
Platform: Steamdeck

**Comment by ebenbruyns** [comment]
I've added a fix for this, it should be in the next test build. It will take a bit of time for it to be released as I'm doing more work in this area too.

**Comment by mrsjunkrunner** [comment]
> I'd like to retain the existing media assets while still updating all other files. Maybe provide an opt in so it isn't the default for all uers.

Hey just wanted to let you know that v1.1.8 in testing should fix this issue. If you wouldn't mind testing it we would appreciate any feedback as to whether or not this does fix it.

Please let us know if you have any further issues with this.

I'll leave it open and if v1.1.8 does fix it would you mind closing this issue.

**Comment by devertonh** [comment]
I was able to confirm that this is working on the current stable version of SteamOS as well with Decky Loader v3.0.0-pre12 and using Junk-Store v 1.1.8-fb9f7702 in testing. 

Thanks so much for fixing this so quickly and the great communication. I appreciate it.

**Comment by mrsjunkrunner** [comment]
> I was able to confirm that this is working on the current stable version of SteamOS as well with Decky Loader v3.0.0-pre12 and using Junk-Store v 1.1.8-fb9f7702 in testing.
> 
> Thanks so much for fixing this so quickly and the great communication. I appreciate it.

Awesome, sorry for the slowness in getting this through. We were waiting on the Decky team to merge it to the testing store. Thanks for getting back to us so quickly letting us know it works!
