### ISSUE TITLE
Legendary not properly logging in via scripts

### ISSUE THREAD

**Issue by MattyXarope** [ebenbruyns/junkstore#8]
From the looks of things, Legendary is not correctly logging in when launching the game given the script that is created and put as a launch command for the game on Steam.

Here is the script created for Prey, in this instance (I've replaced the identifier at the end for the prupose of this bug report):

```
$(/home/deck/homebrew/plugins/Junk-Store/scripts/get-epic-args.sh  identifier)
```

This is the output when trying to execute this bash script in the terminal:

```
(1)(deck@steamdeck ~)$ $(/home/deck/homebrew/plugins/Junk-Store/scripts/get-epic-args.sh identifier)
/home/deck/homebrew/plugins/Junk-Store/scripts/get-epic-args.sh: line 4: /scripts/epic-config.py: No such file or directory
```

So I looked at get-epic-args.sh which contains the following:

```
#!/bin/bash
PLATFORM=Epic
source "${HOME}/homebrew/plugins/Junk-Store/scripts/settings.sh"
$EPICCONF --get-args "${1}"
echo $ARGS
```
Which seemed like a location error for EPICCONF.

So I went to settings.sh and modified the location for EPICCONF to the following:

```
PATH=$HOME/miniconda3/bin:$PATH
DOSCONF="${DECKY_PLUGIN_DIR}/scripts/dosbox-conf.py"
EPICCONF="${HOME}/homebrew/plugins/Junk-Store/scripts/epic-config.py"
EPICDB="${DECKY_PLUGIN_RUNTIME_DIR}/epic.db"
LEGENDARY="/bin/flatpak run com.github.derrod.legendary"
# the install location of the games
INSTALL_DIR="$HOME/Games/epic/"
# the launcher script to use in steam
LAUNCHER="${DECKY_PLUGIN_DIR}/scripts/run-epic.sh"
ARGS_SCRIPT="${DECKY_PLUGIN_DIR}/scripts/get-epic-args.sh"
DBNAME="epic.db"
# database to use for configs and metadata
DBFILE="${DECKY_PLUGIN_RUNTIME_DIR}/epic.db"
```

Which, when saved to settings.sh, displays the following on terminal:

```
(deck@steamdeck ~)$ $(/home/deck/homebrew/plugins/Junk-Store/scripts/get-epic-args.sh identifier)
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
bash: -AUTH_LOGIN=unused: command not found
```

So at this point it is at least logging in, but authentication fails. I'll have to check more closely why this is.

As of now it seems that the games are correctly downloaded (albeit some with bad exe paths #7), but they're not interfacing with Epic Services (Legendary) correctly which will be a problem down the road, especially with multi-player and other online functions.

I've uoloaded the log for Among Us here:
[amongUs.log](https://github.com/ebenbruyns/junkstore/files/13556461/amongUs.log)

This is an online only game that will not progress to the main screen without logging in correctly. It expectedly shows this error:

![447f6403-9b0e-4355-afda-87b247b1ec61](https://github.com/ebenbruyns/junkstore/assets/30245871/b26e96e8-7c31-4c16-886a-3db3732f6a33)

**Comment by ebenbruyns** [comment]
I've isolated the cause of the issue, I just need to find the best solution to this.
