### ISSUE TITLE
Can't login at all

### ISSUE THREAD

**Issue by HollyCeuin** [ebenbruyns/junkstore#9]
Title, if I try to log in via the login button, once I do I just get booted back to the login steam entry without being logged in. 

If i do it via konsole i get 

"Error: logging in failed with Value error('At least one token type must be specified!'), please try again"

**Comment by ebenbruyns** [comment]
there's an issue with legendary at the moment. It's been fixed, but I have to create a new flatpak. In the mean time use

```bash
flatpak run com.github.derrod.legendary auth --disable-webview
```
This will work around the issue for now, once logged in things will work.

**Comment by ebenbruyns** [comment]
I've created a new flatpak, it will take a while before i can update the build in testing - I'm working on a ton of stuff and I'm about to leave the country for 3 weeks. In the mean time you can try installing the new flatpak which should solve the issue:

```bash
    flatpak uninstall com.github.derrod.legendary -y
    cd /tmp
    flatpak --user install flathub org.gnome.Platform//45 -y
    wget https://github.com/ebenbruyns/legendary-flatpak/releases/download/Test-0.2/legendary.flatpak
    flatpak --user install legendary.flatpak -y
    rm legendary.flatpak
```
I hope that helps for now, apologies for not being able to create a proper fix right now, but it's coming with some more really good stuff

**Comment by HollyCeuin** [comment]
The command to disable webview worked, I'll try the new flatpak soon and let you know if it works.

No worries about the proper fix, the workaround is easy enough!

**Comment by HollyCeuin** [comment]
The updated flatpak works, webview login went smoothly.

**Comment by ebenbruyns** [comment]
Thanks for confirming.
